### ISSUE TITLE
Review Breakpoint sizes and naming convention

### ISSUE THREAD

**Issue by cobrien64** [AlaskaAirlines/OrionDesignTokens#10]
https://github.com/AlaskaAirlines/OrionDesignTokens/blob/470c4cb886e533072f4b4af6c54b956cde3957d1/src/breakpoint.json#L7

**Comment by ecommerceUXdesign** [comment]
See updates per the v2.8 branch
https://github.com/AlaskaAirlines/OrionDesignTokens/blob/tokens%402.8/src/breakpoint.json

Closing this issue as the solution is being addressed in the new 2.8 branch.
